action_id: trunk-single-player-auto-upgrade
date: 2023-02-28 00:00:34
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-restart=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 127
  out: ""
  err: "trunk-single-player-auto-upgrade: line 1: trunk: command not found\n"
timestamp: 1677542434
full_timestamp:
  nanos: 784573000
  seconds: 1677542434
trunk_version: 1.3.1
