action_id: trunk-single-player-auto-on-upgrade
date: 2023-02-27 23:05:34
run: trunk on-upgrade --single-player-only -n --no-progress --allow-daemon-restart=false
run_from: ""
trigger: schedule 24h+5m
result:
  exit_code: 127
  out: ""
  err: "trunk-single-player-auto-on-upgrade: line 1: trunk: command not found\n"
timestamp: 1677539134
full_timestamp:
  nanos: 776939000
  seconds: 1677539134
trunk_version: 1.3.1
