action_id: trunk-upgrade-available
date: 2023-02-28 05:00:34
run: trunk upgrade --notify --allow-daemon-restart=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: line 1: trunk: command not found\n"
timestamp: 1677560434
full_timestamp:
  nanos: 780525000
  seconds: 1677560434
trunk_version: 1.3.1
